"""INT-2 non-benchmark retrieval and cache experiment infrastructure."""

from mandateguard.engineering.int2.models import (
    CostEstimate,
    CostRates,
    DownstreamSelection,
    EmbeddingSource,
    ExperimentQuery,
    ExperimentRetrievalResult,
    Int2ExperimentError,
    RelevanceAnnotation,
    RelevanceManifest,
    RetrievalConfiguration,
    RetrievalMetrics,
    RetrievalObservation,
    RetrievalStrategy,
    SUPPORTED_ALPHAS,
    SUPPORTED_TOP_K,
    SelectedRetrievalConfiguration,
    TokenUsage,
    estimate_api_cost,
    retrieval_matrix,
)
from mandateguard.engineering.int2.embeddings import (
    EmbeddingSnapshot,
    MAX_PROVIDER_CALLS,
    UniqueEmbeddingInputs,
    precompute_embeddings,
    text_key,
    unique_embedding_inputs,
)
from mandateguard.engineering.int2.retrieval import (
    ExperimentRetriever,
    compute_retrieval_metrics,
)
from mandateguard.engineering.int2.fixtures import (
    RetrievalQueryCorpus,
    RetrievalQuerySpec,
    build_experiment_queries,
    load_query_corpus,
    load_relevance_manifest,
)
from mandateguard.engineering.int2.sweep import (
    RetrievalSweepHarness,
    StageASweepResult,
    run_stage_a_sweep,
)
from mandateguard.engineering.int2.downstream import (
    AuthorizationTransition,
    DownstreamAuthorizationCase,
    DownstreamAuthorizationObservation,
    execute_selected_downstream,
)
from mandateguard.engineering.int2.cache import (
    CacheExperimentHarness,
    CacheExperimentResult,
    CacheMutationCheck,
    CacheRunObservation,
)
from mandateguard.engineering.int2.artifacts import (
    embedding_experiment_record,
    require_engineering_output,
    retrieval_observation_record,
    write_cache_experiment,
    write_downstream_results,
    write_downstream_selection,
    write_retrieval_artifacts,
)

__all__ = [
    "CostEstimate",
    "CostRates",
    "AuthorizationTransition",
    "CacheExperimentHarness",
    "CacheExperimentResult",
    "CacheMutationCheck",
    "CacheRunObservation",
    "DownstreamAuthorizationCase",
    "DownstreamAuthorizationObservation",
    "DownstreamSelection",
    "EmbeddingSnapshot",
    "EmbeddingSource",
    "ExperimentQuery",
    "ExperimentRetrievalResult",
    "ExperimentRetriever",
    "Int2ExperimentError",
    "MAX_PROVIDER_CALLS",
    "RelevanceAnnotation",
    "RelevanceManifest",
    "RetrievalQueryCorpus",
    "RetrievalQuerySpec",
    "RetrievalConfiguration",
    "RetrievalMetrics",
    "RetrievalObservation",
    "RetrievalStrategy",
    "RetrievalSweepHarness",
    "SUPPORTED_ALPHAS",
    "SUPPORTED_TOP_K",
    "SelectedRetrievalConfiguration",
    "StageASweepResult",
    "TokenUsage",
    "UniqueEmbeddingInputs",
    "compute_retrieval_metrics",
    "build_experiment_queries",
    "embedding_experiment_record",
    "estimate_api_cost",
    "execute_selected_downstream",
    "load_query_corpus",
    "load_relevance_manifest",
    "precompute_embeddings",
    "require_engineering_output",
    "retrieval_observation_record",
    "retrieval_matrix",
    "run_stage_a_sweep",
    "text_key",
    "unique_embedding_inputs",
    "write_cache_experiment",
    "write_downstream_results",
    "write_downstream_selection",
    "write_retrieval_artifacts",
]
