"""INT-2 non-benchmark retrieval and cache experiment infrastructure."""

from mandateguard.engineering.int2.models import (
    CostEstimate,
    CostRates,
    DownstreamSelection,
    ExperimentQuery,
    ExperimentRetrievalResult,
    Int2ExperimentError,
    RelevanceAnnotation,
    RelevanceManifest,
    RetrievalConfiguration,
    RetrievalMetrics,
    RetrievalObservation,
    RetrievalStrategy,
    SUPPORTED_ALPHAS,
    SUPPORTED_TOP_K,
    SelectedRetrievalConfiguration,
    TokenUsage,
    estimate_api_cost,
    retrieval_matrix,
)
from mandateguard.engineering.int2.retrieval import (
    ExperimentRetriever,
    compute_retrieval_metrics,
)
from mandateguard.engineering.int2.fixtures import (
    RetrievalQueryCorpus,
    RetrievalQuerySpec,
    build_experiment_queries,
    load_query_corpus,
    load_relevance_manifest,
)
from mandateguard.engineering.int2.sweep import RetrievalSweepHarness
from mandateguard.engineering.int2.downstream import (
    AuthorizationTransition,
    DownstreamAuthorizationCase,
    DownstreamAuthorizationObservation,
    execute_selected_downstream,
)
from mandateguard.engineering.int2.cache import (
    CacheExperimentHarness,
    CacheExperimentResult,
    CacheMutationCheck,
    CacheRunObservation,
)
from mandateguard.engineering.int2.artifacts import (
    require_engineering_output,
    retrieval_observation_record,
    write_cache_experiment,
    write_downstream_results,
    write_downstream_selection,
    write_retrieval_artifacts,
)

__all__ = [
    "CostEstimate",
    "CostRates",
    "AuthorizationTransition",
    "CacheExperimentHarness",
    "CacheExperimentResult",
    "CacheMutationCheck",
    "CacheRunObservation",
    "DownstreamAuthorizationCase",
    "DownstreamAuthorizationObservation",
    "DownstreamSelection",
    "ExperimentQuery",
    "ExperimentRetrievalResult",
    "ExperimentRetriever",
    "Int2ExperimentError",
    "RelevanceAnnotation",
    "RelevanceManifest",
    "RetrievalQueryCorpus",
    "RetrievalQuerySpec",
    "RetrievalConfiguration",
    "RetrievalMetrics",
    "RetrievalObservation",
    "RetrievalStrategy",
    "RetrievalSweepHarness",
    "SUPPORTED_ALPHAS",
    "SUPPORTED_TOP_K",
    "SelectedRetrievalConfiguration",
    "TokenUsage",
    "compute_retrieval_metrics",
    "build_experiment_queries",
    "estimate_api_cost",
    "execute_selected_downstream",
    "load_query_corpus",
    "load_relevance_manifest",
    "require_engineering_output",
    "retrieval_observation_record",
    "retrieval_matrix",
    "write_cache_experiment",
    "write_downstream_results",
    "write_downstream_selection",
    "write_retrieval_artifacts",
]
